# spring.profiles.active=local
database=h2
spring.sql.init.schema-locations=classpath*:database/fashion_shop.sql
spring.sql.init.data-locations=classpath*:database/data.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG
spring.sql.init.mode=always
# SendGrid Configuration
sendgrid.api-key=SG.dummy_key_for_local_testing_only_1234567890

# OpenAI Configuration
openai.api.url=https://api.groq.com/openai/v1
openai.api.key=YOUR_KEY
openai.api.model=llama-3.3-70b-versatile